### ISSUE TITLE
Add a new README

### ISSUE THREAD

**Issue by jsierles** [rnplay/rnplay-native#1]
This readme should contain:
- Instructions for building for appetize
- Instructions for building for release
- How to develop
- How to setup new packager containers on the RNPlay server

**Comment by sw2262004** [comment]
@jsierles I found there's some issue with the parameter under 
App -> Screen -> CustomerApp.js -> handleSubmit() should be 
reloadApp(this.state.url, '', this.state.appName); instead.

Would appreciate if you could help fix it since I don't have access to the repository.

**Comment by jsierles** [comment]
@sw2262004 Thanks for that! I'll open a new issue for this. You can fork this repository as well, if you wanted to contribute a [pull request](https://help.github.com/articles/using-pull-requests/).

**Comment by dariocravero** [comment]
Quick question on this topic, what's the code's license? Thanks!

**Comment by jsierles** [comment]
Good question! We haven't added one, but I'll do that now (MIT/BSD).

**Comment by dariocravero** [comment]
Thanks :)
