### ISSUE TITLE
Get react-native-mapbox-gl working

### ISSUE THREAD

**Issue by bsudekum** [rnplay/rnplay-native#17]
Hey I saw you added react-native-mapbox-gl, awesome! I put together a [quick demo](https://rnplay.org/apps/euFzXw) but I'm getting the following error: 

![](https://cldup.com/UuyxvbYlCV.png)

Do I need to do anything special to enable it? The only way I've been to reproduce this locally is by removing `react-native-mapbox-gl` from the `node_modules` folder.

**Comment by jsierles** [comment]
Thanks for the report! I'm not sure why this is happening actually. The packager has the module installed,  but it's throwing this error: Unable to resolve module react-native-mapbox-gl. I'll look into it some more.

**Comment by jsierles** [comment]
This is also happening with react-timer-mixin. Still not sure what's up, will keep looking! I've tested this module locally without issue.

**Comment by bsudekum** [comment]
Interesting....

**Comment by bsudekum** [comment]
@jsierles any findings?

**Comment by jsierles** [comment]
Not yet - been swamped with other work lately. if you have any time to check out the iOS app for possible misuse of the plugin, it's appreciated! Otherwise next week I will have time to loop back to this. Sorry for the delay.

**Comment by jsierles** [comment]
Sorry for the accidental closure. Been tracking this down but still no conclusion. It appears even with a full js bundle, this error occurs when running from the app. Going to continue investigating.

**Comment by jsierles** [comment]
This is related to bugs in the 0.8 packager dependency resolver update. 0.10 has a bunch of fixes, so going to start upgrading everything to use that. However, mapbox-gl crashes on 0.10:

```
2015-08-22 20:43:06.156 Playground[27741:1264492] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'customDirectEventTypes must return an array, but RCTMapboxGLManager returned __NSDictionaryI'
```

**Comment by bsudekum** [comment]
Interesting, I'll take a look this weekend.

**Comment by jsierles** [comment]
related 

https://github.com/facebook/react-native/issues/2347

**Comment by jsierles** [comment]
I fixed the issue with the packager! There's a working sample here:

https://rnplay.org/apps/IFLnWQ

However, the map tiles are missing. Perhaps I messed up when including the mapbox assets?

**Comment by jsierles** [comment]
Perhaps some more details: after applying some fixes for 0.10, I get this error with your demo:

```
 <Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
2015-08-23 02:41:41.592 [info][tid:com.facebook.React.JavaScript] { zoom: 0, longitude: 0, latitude: 0 }
libc++abi.dylib: terminating with uncaught exception of type mbgl::util::SpriteImageException: Sprite image dimensions may not be zero
```

I'll post my PR shortly.

**Comment by bsudekum** [comment]
Regarding `However, the map tiles are missing. Perhaps I messed up when including the mapbox assets?`

Looking at the project, it seems like you added and are properly linking to `MapboxGL.bundle` but the bundle was never checked in in git. 

![](https://cldup.com/Q1HVz2NonF.png)

I can put together a PR and add the bundle.

**Comment by jsierles** [comment]
OK - FYI I see the bundle was installed in the build I uploaded to Appetize.

**Comment by bsudekum** [comment]
Yeah, it's a tile loading issue, otherwise the background color would not load if the styles were not there. Is there anyway we can see if there are any errors in the console?

**Comment by jsierles** [comment]
The missing tiles was on 0.8 - and the new error on 0.10. Which should we look at first?

**Comment by jsierles** [comment]
The new error is still happening when I load your example with the 0.10 release. I'd like to push to the app store today. I'll still include it even if we can't solve this, but it would be good to know what's up.

**Comment by akabab** [comment]
@jsierles: having the same issue "SpriteImageException: Sprite image dimensions may not be zero"

**Comment by jsierles** [comment]
I'll take a look again at this soon. At the moment I don't have time, but any help is appreciated!

**Comment by bsudekum** [comment]
Hey could you try updating to react-native-mapbox-gl@0.4.2 (just released) and see if the problem still persist?

**Comment by jsierles** [comment]
Sure thing - will be reviewing all the modules after we get android support out on the site. Unfortunately many are not working properly in the latest build! But we can push them out faster now.

**Comment by jsierles** [comment]
This problem has gone away with the latest release - but I still am not seeing map tiles. Can you check the code here? https://rnplay.org/apps/YmkqXg

**Comment by bsudekum** [comment]
It looks like your loading a non exists at style. In the update, all styles have been updated so Mapbox-streets-v7 is no longer valid. You will need to add the new Mapbox.bundle and also try streets-v8 instead.

**Comment by jsierles** [comment]
I added the latest Mapbox.bundle, and tried ```styleURL={'asset://styles/mapbox-streets-v8.json'}```

But still not seeing the map. Is that asset path correct?

**Comment by bsudekum** [comment]
Little confusing, dropped the Mapbox prefix on the style. It's just streets-v8. You can also view all the styles that ship with the sdk by opening up the Mapbox.bundle.

**Comment by jsierles** [comment]
It works! Looks like we're good - the next iOS release will include the latest Mapbox, and it's available today on the site. I've also added it to the homepage. If you'd like to setup a more complete example or want this one assigned to your account, let me know!

**Comment by bsudekum** [comment]
Awesome!

**Comment by jsierles** [comment]
The app was approved yesteday, and Mapbox finally works! I added your example app to the homepage.

**Comment by bsudekum** [comment]
:100: !!!
