### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by soliury** [rnplay/rnplay-native#19]
Today, I have try rnplay, but I find some problem.

* When go in a project, I don't know how to return to the rnplay, I only can do is to close the app and reopen.

* In Scan Code tabBar, the statusBar have the same color of background, and then , it can't show.

* And some little design bug should fix and to let the app more beauty.

* And my [noder](https://rnplay.org/apps/_2y0Dw) have some bugs in the [react-native-modal](https://github.com/brentvatne/react-native-modal), I think it's the bug of modal in object-c. (You can find this bug in the login panel)

**Comment by jsierles** [comment]
To return to the app, long-press with two fingers for 4 seconds. This is in the 'About' page. We'd like to make it more obvious, not sure how yet!

What's the issue with the tab bar? I can look at restoring the status bar.

I agree - we'd like to make the app look nicer. Contributions are welcome :)

I'll take a look at modal as well. We do include this module, so it should work.

**Comment by soliury** [comment]
ok, When I am free, I will try to improve the app, and submit a PR.

**Comment by soliury** [comment]
I think it's the problem of modal and blur. 

Because the modal include the blur, and my project directly include blur. There may have some bugs.

**Comment by jsierles** [comment]
The tab bar coloring should be fixed now. I'm closing this and opening a new issue for the blur module. Thanks!
