### ISSUE TITLE
Includes react-native-material-kit

### ISSUE THREAD

**Issue by xinthink** [rnplay/rnplay-native#21]
Hi, thanks for the great work!
Would you consider including [react-native-material-kit](https://github.com/xinthink/react-native-material-kit) in the app? It's amazing to put a live demo and playground on the module's home page.

**Comment by jsierles** [comment]
Sure thing! One question, I noticed you mentioned you're porting it to javascript. Is that ready yet or do you want to have the native version included?

**Comment by xinthink** [comment]
Thanks @jsierles, 
There's still some legacy code written in objc, so it's still a native module.

**Comment by jsierles** [comment]
Included in the latest release.

**Comment by xinthink** [comment]
Thanks, it's awesome!
