### ISSUE TITLE
Something was wrong when I use git to push my app to the site

### ISSUE THREAD

**Issue by zhangmengxue** [rnplay/rnplay-native#31]
I was following this [How do I use git to push my app to the site?](https://rnplay.org/about)  

But when I   ```git push rnplay master```  ,there was a problem ```fatal: unable to access 'https://wxLhXZLHG8skja75CRGw:@git.rnplay.org/VD4w6Q.git/': SSL certificate problem: Invalid certificate chain```

I sign in with github , my e-mail address is mengxue.yx@gmail.com.

```javascript
➜  FlipDemo git:(master) rnplay -a
Enter your authentication token:
wxLhXZLHG8skja75CRGw
Please enter your e-mail address:
mengxue.yx@gmail.com
OK: Saved config to ~/.rnplay
➜  FlipDemo git:(master) rnplay -c
We found the following project name: FlipDemo - do you want to use it? y/n
y
INFO: Setting up new git repo
INFO: Adding git remote
OK: Added remote with name `rnplay` and url: `https://wxLhXZLHG8skja75CRGw:@git.rnplay.org/VD4w6Q.git`
OK: All done! Use `git push rnplay master` to push your application.
OK: You can use `rnplay --open` to open this application on rnplay.org
➜  FlipDemo git:(master) ✗ git push rnplay master
fatal: unable to access 'https://wxLhXZLHG8skja75CRGw:@git.rnplay.org/VD4w6Q.git/': SSL certificate problem: Invalid certificate chain
```

**Comment by jsierles** [comment]
Sorry about this! We've disabled git push due to conflicts between modules in our React Native packager setup.

Later we hope to support pushing and hosting app bundles to the site for larger apps. This means no code would be browsable, but we'd support adding a link to a public git repository.

**Comment by zhangmengxue** [comment]
It's just a demo... I've try this way because I found out that I counld only use react native modules in the playground...

**Comment by jsierles** [comment]
Even this way, you could only use native modules supported by the playground. In the future we'll make this easier, but for now can't reenable git push due to this module conflict issue. Sorry!

**Comment by zhangmengxue** [comment]
OK! Hope you are done weller and weller . Thanks for reguards.
