### ISSUE TITLE
Android emulator only shows when both iOS and Android are set to "SUPPORTED"

### ISSUE THREAD

**Issue by jrs-onforce** [rnplay/rnplay-native#7]
Browser: Safari, Firefox, Chrome

Here's a link to a video that shows what's happening.  I've never been able to run the Android emulator with rnplay.  It seems very popular but, well what I don't understand is.

https://www.youtube.com/watch?v=1LaRg85L6HI

1) Why do I have to check both iOS and Android under SUPPORTED, and then click the android tab .. in order to see the android emulator?  Why doesn't simply checking off Android under SUPPORTED show the android emulator?

2) Not even the built-in rnplay sample code works.  What's going on?

Thanks in advance...

**Comment by jsierles** [comment]
We're about to launch a new version based on exponent, along with which these issues will be fixed. Thanks for reporting and for your patience!

**Comment by jsierles** [comment]
We just relaunched with a more stable setup based on Exponent.js. Give it a try and let me know if you have issues!
